# Generated by Django 3.2 on 2023-03-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourites',
        ),
    ]
