# Generated by Django 3.2 on 2023-03-07 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_a_bouquet', '0002_auto_20230307_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouquet',
            old_name='flowers',
            new_name='select_flowers',
        ),
    ]
